### ISSUE TITLE
Sequential VCF parsing

### ISSUE THREAD

**Issue by hammer** [sgkit-dev/sgkit#1183]
@jeromekelleher to bring over https://github.com/pystatgen/sgkit-publication/pull/94, motivated by https://github.com/pystatgen/sgkit/issues/1168. Related to https://github.com/pystatgen/sgkit/issues/1130.

**Comment by jeromekelleher** [comment]
WIP in #1185

**Comment by tomwhite** [comment]
Closing this as [bio2zarr](https://github.com/sgkit-dev/bio2zarr) is now established.
