### ISSUE TITLE
Deprecate functions for reading VCF

### ISSUE THREAD

**Issue by tomwhite** [sgkit-dev/sgkit#1232]
We should encourage people to start using bio2zarr for VCF conversion, rather than the functions in sgkit. We can start the process by deprecating the functions here.

Note that the functions for writing VCF (`write_vcf` and `zarr_to_vcf`) have no equivalents in bio2zarr, and should not be deprecated.

A couple of questions:
1. Are there any missing features we need to implement before deprecating?
2. Should we deprecate before the next release?

(This was discussed a bit in #1228.)

**Comment by jeromekelleher** [comment]
The only features missing revolve around ``max_alt_alleles``, which I think we're probably not going to actually do in bio2zarr unless someone has a compelling reason (https://github.com/sgkit-dev/bio2zarr/issues/18).

So, I think what we have is fine, given that there probably isn't a lot of people using the code.
