### ISSUE TITLE
Make 0.5.0 release to pick up VCF specification?

### ISSUE THREAD

**Issue by hammer** [sgkit-dev/sgkit#817]
Before we put a blog post up, should we do a quick release to pick up @tomwhite's great work on the VCF specification?

**Comment by jeromekelleher** [comment]
SGTM

**Comment by hammer** [comment]
@tomwhite would you have time to cut a release in the next few weeks?

**Comment by hammer** [comment]
Alternatively we might ask @timothymillar to try it out if he is back full time soon

**Comment by tomwhite** [comment]
Happy to do it - but also might be good for @timothymillar to try out the release process.

**Comment by timothymillar** [comment]
I'm happy to have a go at this though I think it requires a maintainer. It looks like this is mostly automated other than docs (https://github.com/pystatgen/sgkit/issues/768) Is https://github.com/pystatgen/sgkit/issues/608#issuecomment-891117795 still up to date for the docs?

**Comment by tomwhite** [comment]
Thanks @timothymillar. It is mainly automated now - there's a bit more discussion about the release process in #765.

You are a member of the pystatgen github org, so you should have sufficient privileges to do a release.

> Is [#608 (comment)](https://github.com/pystatgen/sgkit/issues/608#issuecomment-891117795) still up to date for the docs?

Yes, that's what I used for 0.4.0.

**Comment by timothymillar** [comment]
@tomwhite I don't think I do have the privileges for this, I cant push a tag to `pystatgen/sgkit` and I don't have the "Draft a new release" option in the releases tab.

**Comment by tomwhite** [comment]
@timothymillar I just added you to the sgkit project. You were a member of the pystatgen organisation, but not the sgkit project, which was an oversight - sorry about that!

BTW we should wait until the build is passing again (see #818) before making a release.

**Comment by timothymillar** [comment]
@tomwhite I see #818 is closed but the upstream and GPU builds are still failing. Are we set to make a release or are we waiting for all green?

**Comment by tomwhite** [comment]
The main build is failing too, which needs looking at before we release (#825). Upstream should be checked too. I should have a bit of time next week, but feel free to have a look in the meantime.

**Comment by tomwhite** [comment]
I've managed to get the main build working again (#833), so I can do a release soon (probably next week). We have a complicated set of pinned dependencies, which we'd like to remove over time, but they are needed for the time being.

**Comment by tomwhite** [comment]
We discussed the release process a bit in #765. It should be something like the [tskit release process](https://tskit.dev/tskit/docs/latest/development.html#python).

**Comment by tomwhite** [comment]
## Release instructions

With the latest main branch checked out locally, tag the release:

```shell
VERSION=0.5.0
git tag -a $VERSION -m "Release $VERSION"
git push origin --tags # 'origin' is upstream branch
```

This will run some actions, including one that builds wheels and uploads artifacts to [test PyPI](https://test.pypi.org/project/sgkit/).

Publish a versioned copy of the documentation by following [these instructions](https://github.com/pystatgen/sgkit/issues/608#issuecomment-891117795). (Note, we would like to automate this step, see #768.)

Check the release looks good there, then publish the draft release on the [releases page](https://github.com/pystatgen/sgkit/releases). Publishing this release will cause the github action to deploy to the [production PyPI](https://pypi.org/project/sgkit/). After release, close the GitHub issue milestone of the release.

**Comment by tomwhite** [comment]
Version 0.5.0 is released!
