### ISSUE TITLE
Add `asv` benchmark for compression ratio of some example VCFs

### ISSUE THREAD

**Issue by tomwhite** [sgkit-dev/sgkit#938]
Suggested by @benjeffery in https://github.com/pystatgen/sgkit/pull/937#pullrequestreview-1145718679

**Comment by tomwhite** [comment]
@hammer notes that https://github.com/ionelmc/pytest-benchmark or https://github.com/conbench/conbench are alternatives to ASV.

**Comment by hammer** [comment]
It definitely sounds like `pytest-benchmark` is the simpler starting point.

**Comment by hammer** [comment]
Nvidia made a tool to transform `pytest-benchmark` output to a format expected by `asv` for visualization: https://github.com/rapidsai/asvdb

**Comment by tomwhite** [comment]
It seems that `pytest-benchmark` doesn't support custom metrics that aren't timing-related, i.e. compression ratio in our case here.

https://github.com/coiled/coiled-runtime/issues/186 is worth a read.

**Comment by tomwhite** [comment]
Fixed in #978
